### ISSUE TITLE
Class time discrepancy

### ISSUE THREAD

**Issue by justinttran** [cornell-dti/webdev-class-fall2018#4]
https://github.com/cornell-dti/webdev-class-fall2018#when-does-it-meet says Monday 7:30 - 8:20 PM

https://github.com/cornell-dti/webdev-class-fall2018#when-is-it says Wednesday 8:35 - 9:25 PM

**Comment by abagh0703** [comment]
The one I added (M 7:30-8:20) was from the syllabus draft so I assume the other one is right, but @SheaBelsky  should confirm

**Comment by SheaBelsky** [comment]
It should be Wednesday, sorry.
